// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xeemoihvdxkvjqzvxyep.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhlZW1vaWh2ZHhrdmpxenZ4eWVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNzg5OTgsImV4cCI6MjA2NTc1NDk5OH0.4Ja5sTDiuy-0OjJKIdYs3RuC2dT6L5z4obybBevze_M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);